server:
  port: 8081
#api gateway config
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://codingshuttle.com
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                authenticationEnabled: true
            - name: Authorization
              args:
                allowedRoles: USER,ADMIN,SUPER_ADMIN
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Prem
            - name: Authentication
              args:
                authenticationEnabled: true
            - name: Authorization
              args:
                allowedRoles: ADMIN,SUPER_ADMIN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: sjdkgdfjvbduvsiushvugbjfbuyfbfuydbfuidshfbijsgkjkjfdngbds
